#!/bin/bash

tab="    "

echo -e "\n==================================="
echo -e "This is GenAI CLI-tool setup script."
echo -e "==================================="
sleep 1

echo -e "\nStart Installation..."
sleep 3


# A. Check if Python, Pip, and Virtualenv is existed
echo -e "\nA. Check if Python, Pip, and Virtualenv is existed...\n"
sleep 1

# A-1. Check if Python is existed.
python=`which python`
if [ $? -ne 0 ] ; then
    python=`which python3`
    if  [ $? -ne 0 ] ; then
        echo -e "${tab}* Installation FAILED *"
        echo -e "${tab}* Please install Python/Python3 first *"
        exit
    fi
fi
echo -e "${tab}A-1. You have installed Python ($python)!"
sleep 1

# A-2. Check if Pip is existed.
pip=`which pip`
if [ $? -ne 0 ] ; then
    pip=`which pip3`
    if  [ $? -ne 0 ] ; then
        echo -e "${tab}* Installation FAILED *"
        echo -e "${tab}* Please install Pip/Pip3 first *"
        exit
    fi
fi
echo -e "${tab}A-2. You have installed Pip ($pip)!"
sleep 1

# A-3. Check if Virtualenv is existed.
virtualenv=`$python -m virtualenv --version > /dev/null 2>&1`
if [ $? -ne 0 ] ; then 
    $pip install virtualenv > /dev/null 2>&1
fi
virtualenv=`$python -m virtualenv --version`
echo -e "${tab}A-3. You have installed Virtualenv ($virtualenv)!"
sleep 1


# B. Create virtual envirenments
echo -e "\nB. Create virtual envirenments...\n"
sleep 1

# B-1. Create virtual envirenments
$python -m virtualenv .venv > /dev/null 2>&1
echo -e "${tab}B-1. Virtual envirenments (.venv) is created!"
sleep 1

# B-2. Download necessary python package into venv
$PWD/.venv/bin/pip3 install -r $PWD/requirements.txt > /dev/null 2>&1
echo -e "${tab}B-2. Necessary python packages in requirements.txt are all installed."
sleep 1


# C. Other configurations
echo -e "\nC. Set other configurations\n"
sleep 1

# C-1. Set scripts/configs.py
echo -e "DOTENV_FILEPATH = \"$PWD/.env\"" > $PWD/scripts/configs.py
echo -e "${tab}C-1. Setting scripts/configs.py...Success!"
sleep 1

# C-2 Set .env
echo -e "${tab}C-2. Setting API key created in MakerSuite (https://makersuite.google.com/app/apikey)..."
sleep 1

read -p "${tab}${tab} Please Enter you API key: " apikey
echo -e "GENAI_APIKEY=$apikey\nGENAI_MAX_OUTPUT_TOKENS=300\nGENAI_MODEL=gemini-pro\nGENAI_NAME=Gemini\nGENAI_TEMPERATURE=0.75" > $PWD/.env
unset apikey
echo -e "${tab}${tab} ...Success!\n"
sleep 1


# Complete installation!
echo -e "================================================================================================"
echo -e "\nYou have completed the installation of GenAI CLI-tool!"
echo -e "\nPlease use \`$PWD/.venv/bin/python3 main.py -m <your-question>\` to get a response from GenAI."
echo -e "\nOr use \`$PWD/.venv/bin/python3 main.py -i\` to use the interactive mode."
echo -e "\nYou can also make an alias in your startup file (e.g. ~/.bashrc) to make it more convenient.\n"
echo -e "\nUse \`$PWD/.venv/bin/python3 main.py -h \` to get more information.\n"
echo -e "\nHave fun!\n"
echo -e "================================================================================================"
